title: IT Club - University of Computer Studies (Maubin)
short_title: IT Club
description: IT Club. Student Based Association. We all share our knowledge & experiences each other to become preeminent students & successful computer scientists/technologists in IT World. Founded in December 2017. Located in University of Computer Studies (Maubin)
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
    permalink: "/posts/:path/"
  events:
    output: true
    permalink: "/events/:path/"
  announcements:
    output: true
    permalink: "/announcements/:path/"
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://itclub.netlify.com" # the base hostname & protocol for your site for sitemap
